name: electron-build
on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Clear Electron Builder cache
        if: runner.os == 'Windows'
        run: Remove-Item -Recurse -Force $env:USERPROFILE\.cache\electron-builder
        continue-on-error: true

      # NSIS 설치 경로를 PATH에 추가
      - name: Install NSIS
        if: runner.os == 'Windows'
        run: |
          choco install nsis -y
          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set NSIS_ROOT
        if: runner.os == 'Windows'
        run: echo "NSIS_ROOT=C:\Program Files (x86)\NSIS" >> $env:GITHUB_ENV

      # NSIS 설치 확인
      - name: Verify NSIS Installation
        if: runner.os == 'Windows'
        run: where makensis

      - name: Build/release Electron app
        uses: minai621/action-electron-builder@v1
        with:
          package_root: native
          build_script_name: release
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
