name: electron-build
on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Clear Electron Builder cache
        if: runner.os == 'Windows'
        run: Remove-Item -Recurse -Force $env:USERPROFILE\.cache\electron-builder
        continue-on-error: true

      # NSIS 설치 경로를 PATH에 추가

      - name: Download and Install NSIS 3.0.4.1
        if: runner.os == 'Windows'
        run: |
          $nsisUrl = "https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z"
          $nsisPath = "$env:TEMP\nsis-3.0.4.1.7z"
          Invoke-WebRequest -Uri $nsisUrl -OutFile $nsisPath
          7z x $nsisPath -o"$env:ProgramFiles (x86)\nsis-3.0.4.1" -y
          echo "$env:ProgramFiles (x86)\nsis-3.0.4.1" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        continue-on-error: true

      - name: Set NSIS_ROOT for 3.0.4.1
        run: echo "NSIS_ROOT=$env:ProgramFiles (x86)\nsis-3.0.4.1" >> $env:GITHUB_ENV

      # NSIS 설치 확인
      - name: Verify NSIS Installation
        if: runner.os == 'Windows'
        run: where makensis

      - name: Build/release Electron app
        uses: minai621/action-electron-builder@v1
        with:
          package_root: native
          build_script_name: release
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
