name: electron-build
on: push
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install NSIS on Windows
        if: runner.os == 'Windows'
        run: choco install nsis

      - name: Add NSIS to PATH
        if: runner.os == 'Windows'
        run: echo "::add-path::C:\\Program Files (x86)\\NSIS"

      - name: Verify NSIS Installation
        if: runner.os == 'Windows'
        run: makensis -VERSION

      - name: Clear Electron Builder cache
        run: pnpx electron-builder --reset-cache

      - name: Build/release Electron app
        uses: minai621/action-electron-builder@v1
        with:
          package_root: native
          build_script_name: release
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
