name: electron-windows-nsis-build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Install NSIS
        run: |
          $url = "https://sourceforge.net/projects/nsis/files/NSIS%203/3.04/nsis-3.04.zip/download"
          $output = "$env:TEMP\nsis-3.04.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath "C:\Program Files (x86)\NSIS" -Force
          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Install Dependencies
        run: pnpm install --prefer-offline --no-frozen-lockfile
        working-directory: ./native

      - name: Build Electron App
        run: pnpm run build
        working-directory: ./native

      - name: Create NSIS Installer
        run: pnpx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./native

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./native/release/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
