name: electron-windows-nsis-build

on:
  push:
    branches:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
          sudo apt-get update
          sudo apt-get install -y --install-recommends winehq-stable

      - name: Install Dependencies
        run: pnpm install --prefer-offline --no-frozen-lockfile
        working-directory: ./native

      - name: Build Electron App
        run: pnpm run build
        working-directory: ./native

      - name: Create NSIS Installer
        run: pnpx electron-builder --win --publish always
        working-directory: ./native
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./native/release/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
